kind: pipeline
name: default

steps:
  - name: test3
    image: python
    commands:
    - cd tests
    - pwd
    - pip install -r requirements.txt
    - pytest -vvv

  - name: test4
    image: python
    commands:
    - cd tests
    - pip install -r requirements.txt
    - pytest -vvv

  - name: test
    image: python
    commands:
    - cd tests
    - pwd
    - pip install -r requirements.txt
    - pytest -vvv