kind: pipeline
name: default

steps:
  - name: test
    image: python
    commands:
    - cd tests
    - pwd
    - pip install -r requirements.txt
    - pytest -vvv

  - name: test2
    image: ubuntu
    commands:
    - ls