kind: pipeline
name: default

steps:
- name: web
  image: python
  detach: true
  commands:
  - cd web
  - pip install -r requirements.txt
  - python app.py

- name: test
  image: python
  commands:
  - cd tests
  - pip install -r requirements.txt
  - pytest -vvv

- name: notify
  image: drillster/drone-email
  host: smtp.gmail.com
  username: itay.m@minutemedia.com
  password: from_secret: GMAIL_PASSWORD
  from: drone@your-domain.com
  when:
    status: [ success, failure ]