kind: pipeline
name: default

steps:
- name: test
  image: python
  commands:
  - pip install pytest
  - cd tests
  - pytest -vvv

services:
- name: app
  image: python
  commans:
  - cd web
  - pip install requirements.txt
  - python app.py