kind: pipeline
name: default

steps:
- name: test
  image: python
  commands:
  - cd tests
  - pip install -r requirements.txt
  - pytest -vvv

services:
- name: app
  image: python
  commans:
  - cd web
  - pwd
  - pip install -r requirements.txt
  - python app.py