kind: pipeline
name: default

steps:
- name: web
  image: python
  detach: true
  commands:
  - cd web
  - pip install -r requirements.txt
  - python app.py

- name: go
  image: golang:alpine
  commands:
  - go build -o main .
  - CMD ["./main"]
  detach: true

- name: test
  image: python
  commands:
  - cd tests
  - pip install -r requirements.txt
  - pytest

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: ci
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job. {{build.link}}
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}
  when:
    status: [ success, failure ]