kind: pipeline
name: default

steps:
- name: web
  image: python
  detach: true
  commands:
  - cd web
  - pip install -r requirements.txt
  - python app.py

- name: test
  image: python
  commands:
  - cd tests
  - pip install -r requirements.txt
  - pytest -vvv

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: ci
  when:
    status: [ success, failure ]