kind: pipeline
name: default

steps:
  - name: itay
    image: ubuntu
    commans:
    - pwd

  - name: hello
    image: ubuntu
    commans:
    - pwd

  - name: test
    image: python
    commands:
    - cd tests
    - pwd
    - pip install -r requirements.txt
    - pytest -vvv